//
// File generated by rootcint at Wed Feb  5 20:16:26 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DavidAnaCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DavidAnaCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      namespace larlight {

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::larlight::DavidAna DavidAna;
      #else
      class DavidAna  :  public ::larlight::ana_base {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~DavidAna() throw() {};
         ::TH1D* tpc_evno; //
      };
      #endif
      } 
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void larlightcLcLDavidAna_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void larlightcLcLDavidAna_Dictionary();
   static void *new_larlightcLcLDavidAna(void *p = 0);
   static void *newArray_larlightcLcLDavidAna(Long_t size, void *p);
   static void delete_larlightcLcLDavidAna(void *p);
   static void deleteArray_larlightcLcLDavidAna(void *p);
   static void destruct_larlightcLcLDavidAna(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::larlight::DavidAna*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::larlight::DavidAna) == sizeof(::ROOT::Shadow::larlight::DavidAna));
      ::larlight::DavidAna *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::larlight::DavidAna),0);
      static ::ROOT::TGenericClassInfo 
         instance("larlight::DavidAna", "./DavidAna.hh", 31,
                  typeid(::larlight::DavidAna), DefineBehavior(ptr, ptr),
                  &larlightcLcLDavidAna_ShowMembers, &larlightcLcLDavidAna_Dictionary, isa_proxy, 4,
                  sizeof(::larlight::DavidAna) );
      instance.SetNew(&new_larlightcLcLDavidAna);
      instance.SetNewArray(&newArray_larlightcLcLDavidAna);
      instance.SetDelete(&delete_larlightcLcLDavidAna);
      instance.SetDeleteArray(&deleteArray_larlightcLcLDavidAna);
      instance.SetDestructor(&destruct_larlightcLcLDavidAna);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::larlight::DavidAna*)
   {
      return GenerateInitInstanceLocal((::larlight::DavidAna*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::larlight::DavidAna*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void larlightcLcLDavidAna_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::larlight::DavidAna*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void larlightcLcLDavidAna_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class larlight::DavidAna.
      typedef ::ROOT::Shadow::larlight::DavidAna ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::larlight::DavidAna*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tpc_evno", &sobj->tpc_evno);
      R__insp.GenericShowMembers("larlight::ana_base", ( ::larlight::ana_base * )( (::larlight::DavidAna*) obj ), false);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_larlightcLcLDavidAna(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::larlight::DavidAna : new ::larlight::DavidAna;
   }
   static void *newArray_larlightcLcLDavidAna(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::larlight::DavidAna[nElements] : new ::larlight::DavidAna[nElements];
   }
   // Wrapper around operator delete
   static void delete_larlightcLcLDavidAna(void *p) {
      delete ((::larlight::DavidAna*)p);
   }
   static void deleteArray_larlightcLcLDavidAna(void *p) {
      delete [] ((::larlight::DavidAna*)p);
   }
   static void destruct_larlightcLcLDavidAna(void *p) {
      typedef ::larlight::DavidAna current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::larlight::DavidAna

/********************************************************
* DavidAnaCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDavidAnaCint();

extern "C" void G__set_cpp_environmentDavidAnaCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("DavidAna.hh");
  G__add_compiledheader("DavidAna-TypeDef.hh");
  G__cpp_reset_tagtableDavidAnaCint();
}
#include <new>
extern "C" int G__cpp_dllrevDavidAnaCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* larlight::DavidAna */
static int G__DavidAnaCint_844_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   larlight::DavidAna* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new larlight::DavidAna[n];
     } else {
       p = new((void*) gvp) larlight::DavidAna[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new larlight::DavidAna;
     } else {
       p = new((void*) gvp) larlight::DavidAna;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DavidAnaCint_844_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   larlight::DavidAna* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new larlight::DavidAna(*(larlight::DavidAna*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef larlight::DavidAna G__TlarlightcLcLDavidAna;
static int G__DavidAnaCint_844_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (larlight::DavidAna*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((larlight::DavidAna*) (soff+(sizeof(larlight::DavidAna)*i)))->~G__TlarlightcLcLDavidAna();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (larlight::DavidAna*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((larlight::DavidAna*) (soff))->~G__TlarlightcLcLDavidAna();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DavidAnaCint_844_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   larlight::DavidAna* dest = (larlight::DavidAna*) G__getstructoffset();
   *dest = *(larlight::DavidAna*) libp->para[0].ref;
   const larlight::DavidAna& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* larlight::DavidAna */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDavidAnaCint {
 public:
  G__Sizep2memfuncDavidAnaCint(): p(&G__Sizep2memfuncDavidAnaCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDavidAnaCint::*p)();
};

size_t G__get_sizep2memfuncDavidAnaCint()
{
  G__Sizep2memfuncDavidAnaCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDavidAnaCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna))) {
     larlight::DavidAna *G__Lderived;
     G__Lderived=(larlight::DavidAna*)0x1000;
     {
       larlight::ana_base *G__Lpbase=(larlight::ana_base*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna),G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLana_base),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       larlight::larlight_base *G__Lpbase=(larlight::larlight_base*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna),G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLlarlight_base),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDavidAnaCint() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::wire>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::fifo>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::pulse>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::hit>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,int>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,int>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,bool>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<double> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::vector<double> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<double,allocator<double> >,less<string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<int> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::vector<int> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<int,allocator<int> >,less<string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<std::string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::vector<string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> > >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> >,less<string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<bool> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::vector<bool> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<bool,allocator<bool> > >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<bool,allocator<bool> >,less<string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::user_info>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVector3>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETVector3cOallocatorlETVector3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETVector3cOallocatorlETVector3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETVector3cOallocatorlETVector3gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixD>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixT<double> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<Double_t> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Double_t> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::track>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::cluster>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<Int_t>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::part_mc>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::spacepoint>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::shower>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<larlight::calorimetry>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DavidAnaCintLN_vectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__DavidAnaCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* larlight::DavidAna */
static void G__setup_memvarlarlightcLcLDavidAna(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna));
   { larlight::DavidAna *p; p=(larlight::DavidAna*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DavidAnaCintLN_TH1D),-1,-1,2,"tpc_evno=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDavidAnaCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfunclarlightcLcLDavidAna(void) {
   /* larlight::DavidAna */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna));
   G__memfunc_setup("DavidAna",760,G__DavidAnaCint_844_0_1, 105, G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("initialize",1074,(G__InterfaceMethod) NULL,103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("analyze",756,(G__InterfaceMethod) NULL,103, -1, -1, 0, 1, 1, 1, 0, "U 'larlight::storage_manager' - 0 - storage", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("finalize",850,(G__InterfaceMethod) NULL,103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("DavidAna", 760, G__DavidAnaCint_844_0_5, (int) ('i'), G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna), -1, 0, 1, 1, 1, 0, "u 'larlight::DavidAna' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DavidAna", 886, G__DavidAnaCint_844_0_6, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DavidAnaCint_844_0_7, (int) ('u'), G__get_linked_tagnum(&G__DavidAnaCintLN_larlightcLcLDavidAna), -1, 1, 1, 1, 1, 0, "u 'larlight::DavidAna' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDavidAnaCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDavidAnaCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDavidAnaCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DavidAnaCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_larlight = { "larlight" , 110 , -1 };
G__linked_taginfo G__DavidAnaCintLN_larlightcLcLlarlight_base = { "larlight::larlight_base" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgR = { "vector<larlight::wire,allocator<larlight::wire> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::wire,allocator<larlight::wire> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgR = { "vector<larlight::fifo,allocator<larlight::fifo> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::fifo,allocator<larlight::fifo> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgR = { "vector<larlight::pulse,allocator<larlight::pulse> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::pulse,allocator<larlight::pulse> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgR = { "vector<larlight::hit,allocator<larlight::hit> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::hit,allocator<larlight::hit> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR = { "map<string,vector<double,allocator<double> >,less<string>,allocator<pair<const string,vector<double,allocator<double> > > > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR = { "map<string,vector<int,allocator<int> >,less<string>,allocator<pair<const string,vector<int,allocator<int> > > > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR = { "map<string,vector<string,allocator<string> >,less<string>,allocator<pair<const string,vector<string,allocator<string> > > > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR = { "map<string,vector<bool,allocator<bool> >,less<string>,allocator<pair<const string,vector<bool,allocator<bool> > > > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgR = { "vector<larlight::user_info,allocator<larlight::user_info> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::user_info,allocator<larlight::user_info> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlETVector3cOallocatorlETVector3gRsPgR = { "vector<TVector3,allocator<TVector3> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVector3,allocator<TVector3> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR = { "vector<TMatrixT<double>,allocator<TMatrixT<double> > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMatrixT<double>,allocator<TMatrixT<double> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgR = { "vector<larlight::track,allocator<larlight::track> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::track,allocator<larlight::track> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgR = { "vector<larlight::cluster,allocator<larlight::cluster> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::cluster,allocator<larlight::cluster> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR = { "set<int,less<int>,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgR = { "vector<larlight::part_mc,allocator<larlight::part_mc> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::part_mc,allocator<larlight::part_mc> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgR = { "vector<larlight::spacepoint,allocator<larlight::spacepoint> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::spacepoint,allocator<larlight::spacepoint> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgR = { "vector<larlight::shower,allocator<larlight::shower> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::shower,allocator<larlight::shower> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_vectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgR = { "vector<larlight::calorimetry,allocator<larlight::calorimetry> >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgRcLcLiteratorgR = { "reverse_iterator<vector<larlight::calorimetry,allocator<larlight::calorimetry> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_larlightcLcLstorage_manager = { "larlight::storage_manager" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_larlightcLcLana_base = { "larlight::ana_base" , 99 , -1 };
G__linked_taginfo G__DavidAnaCintLN_larlightcLcLDavidAna = { "larlight::DavidAna" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDavidAnaCint() {
  G__DavidAnaCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DavidAnaCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TH1D.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_larlight.tagnum = -1 ;
  G__DavidAnaCintLN_larlightcLcLlarlight_base.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlETVector3cOallocatorlETVector3gRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_vectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DavidAnaCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__DavidAnaCintLN_larlightcLcLstorage_manager.tagnum = -1 ;
  G__DavidAnaCintLN_larlightcLcLana_base.tagnum = -1 ;
  G__DavidAnaCintLN_larlightcLcLDavidAna.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDavidAnaCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TH1D);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_larlight);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_larlightcLcLlarlight_base);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLwirecOallocatorlElarlightcLcLwiregRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLfifocOallocatorlElarlightcLcLfifogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpulsecOallocatorlElarlightcLcLpulsegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLhitcOallocatorlElarlightcLcLhitgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLuser_infocOallocatorlElarlightcLcLuser_infogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlETVector3cOallocatorlETVector3gRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLtrackcOallocatorlElarlightcLcLtrackgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLclustercOallocatorlElarlightcLcLclustergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLpart_mccOallocatorlElarlightcLcLpart_mcgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLspacepointcOallocatorlElarlightcLcLspacepointgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLshowercOallocatorlElarlightcLcLshowergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_vectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_reverse_iteratorlEvectorlElarlightcLcLcalorimetrycOallocatorlElarlightcLcLcalorimetrygRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_larlightcLcLstorage_manager);
   G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_larlightcLcLana_base);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DavidAnaCintLN_larlightcLcLDavidAna),sizeof(larlight::DavidAna),-1,263424,(char*)NULL,G__setup_memvarlarlightcLcLDavidAna,G__setup_memfunclarlightcLcLDavidAna);
}
extern "C" void G__cpp_setupDavidAnaCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupDavidAnaCint()");
  G__set_cpp_environmentDavidAnaCint();
  G__cpp_setup_tagtableDavidAnaCint();

  G__cpp_setup_inheritanceDavidAnaCint();

  G__cpp_setup_typetableDavidAnaCint();

  G__cpp_setup_memvarDavidAnaCint();

  G__cpp_setup_memfuncDavidAnaCint();
  G__cpp_setup_globalDavidAnaCint();
  G__cpp_setup_funcDavidAnaCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDavidAnaCint();
  return;
}
class G__cpp_setup_initDavidAnaCint {
  public:
    G__cpp_setup_initDavidAnaCint() { G__add_setup_func("DavidAnaCint",(G__incsetup)(&G__cpp_setupDavidAnaCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDavidAnaCint() { G__remove_setup_func("DavidAnaCint"); }
};
G__cpp_setup_initDavidAnaCint G__cpp_setup_initializerDavidAnaCint;

