
CXX		= g++
LD              = g++
LDFLAGS         += -Wl,-rpath,$(MAKE_TOP_DIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O2 -std=c++0x -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = g++
SOFLAGS         = -g -shared 
